require "activeadmin" 
require "activeadmin_addons"  
require "active_admin_role" 
require "devise" 
require "draper" 
require "pundit" 
require "enumerize"  
require "ckeditor"  
require "chartkick"  
require "groupdate"  
# require "aasm" 


# require "amz/core/engine"   
require "amz/backend/authorization"  
require "amz/backend/engine"  
require "amz/backend/paranoia/core"   
require "amz/backend/batch/dsl"  
require "amz/backend/state_machine/dsl"  
require "amz/backend/friendly_id/dsl"  
require "amz/backend/tab/dsl"   
require "amz/backend/views/index_as_upload"   
require "amz/backend/views/index_as_jstree"   
require "amz/backend/formtastic/inputs/action_text_input"   
require "amz/backend/controller/active_admin_base"  
